(()=>{
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const base=window.AURA_DATA||{};
  let data=structuredClone(base);
  let currentCategory='Todas';
  let editMode=false;
  let lightboxKind='';
  let lightboxItems=[];
  let lightboxIndex=0;
  const previewMode=new URLSearchParams(location.search).get('preview')==='1';
  function deepMerge(t,s){if(!s||typeof s!=='object')return t;for(const k of Object.keys(s)){if(Array.isArray(s[k]))t[k]=s[k];else if(s[k]&&typeof s[k]==='object')t[k]=deepMerge(t[k]||{},s[k]);else t[k]=s[k]}return t}
  function esc(v=''){return String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
  function setText(sel,val,path){const el=$(sel);if(!el)return;el.textContent=val??'';if(path)el.dataset.editKey=path}
  function setVisible(el,v){if(el)el.hidden=v===false}
  function waUrl(){const num=String(data.contact?.whatsapp||'').replace(/\D/g,'');return `https://wa.me/${num}?text=${encodeURIComponent(data.contact?.whatsappMessage||'')}`}

  function applyMeta(){document.title=data.meta?.siteTitle||'Aura Digital';const d=$('meta[name=description]');if(d)d.content=data.meta?.siteDescription||'';const map={'meta[property="og:title"]':data.meta?.ogTitle,'meta[property="og:description"]':data.meta?.ogDescription,'meta[property="og:image"]':data.meta?.ogImage,'meta[property="og:url"]':data.meta?.siteUrl};for(const [s,v] of Object.entries(map)){const el=$(s);if(el)el.content=v||''}}
  function applyTheme(){const b=data.brand||{},r=document.documentElement;const vars={'--primary':b.primary,'--primary-soft':b.primarySoft,'--accent':b.accent,'--accent-soft':b.accentSoft,'--bg':b.background,'--surface':b.surface,'--text':b.text,'--muted':b.muted,'--border':b.border,'--hero-gradient':b.heroGradient,'--cta-gradient':b.ctaGradient,'--button-gradient':b.buttonGradient,'--heading-font':b.headingFont,'--body-font':b.bodyFont,'--script-font':b.scriptFont,'--heading-scale':b.headingScale||1,'--body-scale':b.bodyScale||1,'--radius':`${Number(b.radius)||24}px`,'--shadow-alpha':Number(b.shadowStrength)||.11,'--logo-height':`${Number(b.logoMaxHeight)||58}px`};for(const [k,v] of Object.entries(vars))if(v!=null)r.style.setProperty(k,v);const isDark=/^#(?:0[0-9a-f]|1[0-9a-f]|2[0-9a-f]|3[0-9a-f])/i.test(String(b.background||''));const configured=b.logo||'assets/logo-transparent.png';const logoSrc=isDark&&configured==='assets/logo-transparent.png'?'assets/logo-dark.png':configured;$$('[data-logo]').forEach(el=>{el.src=logoSrc;el.alt=b.name||'Aura Digital';el.dataset.editKey='brand.logo';if(b.logoMaxHeight)el.style.height=`${b.logoMaxHeight}px`});$$('[data-brand-name]').forEach(el=>{el.textContent=b.name||'Aura Digital';el.dataset.editKey='brand.name'})}

  function navItems(){
    const defaults=base.nav?.items||[],current=Array.isArray(data.nav?.items)?data.nav.items:[];
    const map=new Map(current.map((x,i)=>[String(x?.target||''),{...x,_index:i}]));
    const merged=defaults.map(d=>Object.assign({},d,map.get(String(d.target))||{}));
    current.forEach((x,i)=>{if(x?.target&&!merged.some(y=>String(y.target)===String(x.target)))merged.push({...x,_index:i})});
    return merged.filter(x=>x.visible!==false);
  }
  function renderNav(){const items=navItems();const html=items.map(x=>`<a href="#${esc(x.target)}" data-edit-key="nav.items.${Math.max(0,x._index??(data.nav.items||[]).findIndex(y=>y.target===x.target))}.label">${esc(x.label)}</a>`).join('');$('[data-nav-links]').innerHTML=html;$('[data-mobile-menu]').innerHTML=`<div class="mobile-menu-head"><span>MENÚ</span><strong>${esc(data.brand?.name||'Aura Digital')}</strong></div><nav>${html}</nav><a class="btn btn-primary mobile-menu-cta" href="${waUrl()}" target="_blank" rel="noopener" data-edit-key="nav.cta">${esc(data.nav?.cta||'WhatsApp')}</a>`;$('[data-footer-links]').innerHTML=items.slice(1).map(x=>`<a href="#${esc(x.target)}">${esc(x.label)}</a>`).join('');setText('[data-nav-cta]',data.nav?.cta||'Cotiza por WhatsApp','nav.cta');$$('[data-wa]').forEach(a=>a.href=waUrl())}

  function renderHero(){const h=data.hero||{};setVisible($('[data-section="hero"]'),h.visible);setText('[data-hero-eyebrow]',h.eyebrow,'hero.eyebrow');setText('[data-hero-title]',h.title,'hero.title');setText('[data-hero-text]',h.text,'hero.text');setText('[data-hero-primary]',h.primaryButton,'hero.primaryButton');setText('[data-hero-secondary]',h.secondaryButton,'hero.secondaryButton');const img=$('[data-hero-image]');const mobileSource=$('[data-hero-mobile-source]');if(img){img.src=h.image||'';const fx=Number(h.imageFocusX??50),fy=Number(h.imageFocusY??50),mfx=Number(h.mobileImageFocusX??fx),mfy=Number(h.mobileImageFocusY??fy);img.style.objectPosition=`${fx}% ${fy}%`;img.style.setProperty('--hero-focus-x',`${fx}%`);img.style.setProperty('--hero-focus-y',`${fy}%`);img.style.setProperty('--hero-mobile-focus-x',`${mfx}%`);img.style.setProperty('--hero-mobile-focus-y',`${mfy}%`);img.dataset.editKey=window.matchMedia('(max-width: 720px)').matches?'hero.mobileImage':'hero.image';if(mobileSource)mobileSource.srcset=h.mobileImage||h.image||''}const sl=$('[data-hero-secondary-link]');if(sl)sl.href='#'+(h.secondaryTarget||'servicios');const hero=$('[data-section="hero"]');if(hero){hero.dataset.visualStyle=h.visualStyle||'editorial';hero.style.setProperty('--hero-overlay',String(Number(h.overlay)||0))}const box=$('[data-benefits]');box.innerHTML=(data.benefits||[]).filter(x=>x.visible!==false).map(x=>{const i=data.benefits.indexOf(x);return `<div class="benefit" data-edit-key="benefits.${i}.title"><span>${esc(x.icon)}</span><strong>${esc(x.title)}</strong></div>`}).join('')}

  function renderServices(){setText('[data-services-eyebrow]',data.servicesIntro?.eyebrow,'servicesIntro.eyebrow');setText('[data-services-title]',data.servicesIntro?.title,'servicesIntro.title');setText('[data-services-text]',data.servicesIntro?.text,'servicesIntro.text');$('[data-service-grid]').innerHTML=(data.services||[]).filter(x=>x.visible!==false).map(s=>{const i=data.services.indexOf(s);return `<article class="service-card"><a class="service-image" href="#${esc(s.target)}"><img src="${esc(s.image)}" alt="${esc(s.title)}" data-edit-key="services.${i}.image"></a><div class="service-body"><h3 data-edit-key="services.${i}.title">${esc(s.title)}</h3><p data-edit-key="services.${i}.text">${esc(s.text)}</p><a class="text-link" href="#${esc(s.target)}" data-edit-key="services.${i}.button">${esc(s.button)} <span>→</span></a></div></article>`}).join('')}

  function itemCard(x,kind,index,layout,showTitles=true,showSubtitles=true){const path=kind==='invitation'?`invitationGallery.items.${index}`:`features.${kind}.examples.${index}`;const title=showTitles?`<strong data-edit-key="${path}.title">${esc(x.title||'Proyecto')}</strong>`:'';const sub=showSubtitles&&x.subtitle?`<span data-edit-key="${path}.subtitle">${esc(x.subtitle)}</span>`:'';const demo=x.url?`<em class="demo-hint">Ver demo ↗</em>`:'';const ratio=x.cardRatio||(kind==='invitation'?'portrait':'landscape');return `<button type="button" class="gallery-card ratio-${esc(ratio)}" data-gallery-item data-kind="${esc(kind)}" data-id="${esc(x.id||String(index))}"><div class="gallery-image"><img src="${esc(x.image)}" alt="${esc(x.title||'Ejemplo')}" style="object-position:${Number(x.focusX??50)}% ${Number(x.focusY??50)}%" data-edit-key="${path}.image"></div>${title||sub||demo?`<div class="gallery-card-copy">${title}${sub}${demo}</div>`:''}</button>`}
  function renderInvitationGallery(){const g=data.invitationGallery||{};setVisible($('[data-section="invitationGallery"]'),g.visible);setText('[data-gallery-eyebrow]',g.eyebrow,'invitationGallery.eyebrow');setText('[data-gallery-title]',g.title,'invitationGallery.title');setText('[data-gallery-text]',g.text,'invitationGallery.text');let cats=[...(g.categories||[])].filter(Boolean);if(!cats.includes('Todas'))cats.unshift('Todas');if(!cats.includes(currentCategory))currentCategory='Todas';$('[data-gallery-filters]').innerHTML=cats.map(c=>`<button type="button" class="filter ${c===currentCategory?'active':''}" data-category="${esc(c)}">${esc(c)}</button>`).join('');$$('[data-category]').forEach(b=>b.addEventListener('click',()=>{currentCategory=b.dataset.category;renderInvitationGallery()}));const all=g.items||[];const items=all.map((x,i)=>({x,i})).filter(({x})=>x.visible!==false&&(currentCategory==='Todas'||x.category===currentCategory));const grid=$('[data-gallery-grid]');grid.className=`invitation-gallery layout-${g.layout||'editorial'} ratio-${g.cardRatio||'portrait'}`;grid.innerHTML=items.length?items.map(({x,i})=>itemCard(x,'invitation',i,g.layout,g.showTitles!==false,g.showSubtitles!==false)).join(''):`<div class="empty-gallery">Aún no hay ejemplos en esta categoría.</div>`;bindGalleryCards()}

  function renderFeature(key){
    const f=data.features?.[key],mount=$(`[data-feature-section="${key}"]`);if(!mount||!f)return;setVisible(mount,f.visible);if(f.visible===false)return;
    const reverse=mount.classList.contains('alt');
    const examples=(f.examples||[]).map((x,i)=>({x,i})).filter(({x})=>x.visible!==false);
    const examplesHtml=examples.map(({x,i})=>itemCard(x,key,i,f.galleryLayout,f.showTitles!==false,f.showSubtitles!==false)).join('');
    const featureLink=f.button?`<a class="feature-link" href="#${key}-examples" data-edit-key="features.${key}.button"><span>${esc(f.button)}</span><i aria-hidden="true">↓</i></a>`:'';
    const examplesSection=examples.length?`<div class="feature-examples" id="${key}-examples">
        <div class="feature-examples-head"><div><span class="kicker">PROYECTOS</span><h3 data-edit-key="features.${key}.examplesTitle">${esc(f.examplesTitle||'Ejemplos')}</h3></div></div>
        <div class="feature-gallery layout-${f.galleryLayout||'editorial'}" data-inline-gallery="${key}">${examplesHtml}</div>
      </div>`:'';
    mount.innerHTML=`<div class="container feature-block">
      <div class="feature ${reverse?'reverse':''}">
        <div class="feature-copy"><div class="kicker" data-edit-key="features.${key}.eyebrow">${esc(f.eyebrow)}</div><h2 class="display" data-edit-key="features.${key}.title">${esc(f.title)}</h2><p data-edit-key="features.${key}.text">${esc(f.text)}</p><div class="point-grid">${(f.points||[]).map((p,i)=>`<div data-edit-key="features.${key}.points"><span>✦</span>${esc(p)}</div>`).join('')}</div>${featureLink}</div>
        <div class="feature-image"><img src="${esc(f.image)}" alt="${esc(f.title)}" data-edit-key="features.${key}.image"></div>
      </div>
      ${examplesSection}
    </div>`;
    bindGalleryCards();
  }

  function renderWhy(){setVisible($('[data-section="why"]'),data.why?.visible);setText('[data-why-eyebrow]',data.why?.eyebrow,'why.eyebrow');setText('[data-why-title]',data.why?.title,'why.title');$('[data-why-grid]').innerHTML=(data.why?.items||[]).filter(x=>x.visible!==false).map(x=>{const i=data.why.items.indexOf(x);return `<article class="why-card"><span class="why-icon">${esc(x.icon||'✦')}</span><h3 data-edit-key="why.items.${i}.title">${esc(x.title)}</h3><p data-edit-key="why.items.${i}.text">${esc(x.text)}</p></article>`}).join('')}
  function renderProcess(){setVisible($('[data-section="process"]'),data.process?.visible);setText('[data-process-eyebrow]',data.process?.eyebrow,'process.eyebrow');setText('[data-process-title]',data.process?.title,'process.title');$('[data-process-grid]').innerHTML=(data.process?.items||[]).map((x,i)=>`<article class="process-item"><span>${esc(x.number)}</span><div><h3 data-edit-key="process.items.${i}.title">${esc(x.title)}</h3><p data-edit-key="process.items.${i}.text">${esc(x.text)}</p></div></article>`).join('')}
  function renderCtaFooter(){setVisible($('[data-section="cta"]'),data.cta?.visible);setText('[data-cta-eyebrow]',data.cta?.eyebrow,'cta.eyebrow');setText('[data-cta-title]',data.cta?.title,'cta.title');setText('[data-cta-text]',data.cta?.text,'cta.text');setText('[data-cta-button]',data.cta?.button,'cta.button');setText('[data-footer-note]',data.footer?.note,'footer.note');setText('[data-footer-tagline]',data.footer?.tagline,'footer.tagline');const socials=[];if(data.contact?.instagram&&data.contact.instagram!=='#')socials.push(`<a href="${esc(data.contact.instagram)}" target="_blank" rel="noopener">Instagram</a>`);if(data.contact?.facebook&&data.contact.facebook!=='#')socials.push(`<a href="${esc(data.contact.facebook)}" target="_blank" rel="noopener">Facebook</a>`);if(data.contact?.tiktok&&data.contact.tiktok!=='#')socials.push(`<a href="${esc(data.contact.tiktok)}" target="_blank" rel="noopener">TikTok</a>`);$('[data-social-links]').innerHTML=socials.join('')}

  function applySectionOrder(){const order=data.layout?.sectionOrder||[];const main=$('main');if(!main)return;main.style.display='flex';main.style.flexDirection='column';const visible=k=>{if(k==='hero')return data.hero?.visible!==false;if(k==='invitationGallery')return data.invitationGallery?.visible!==false;if(['menus','web','galleries'].includes(k))return data.features?.[k]?.visible!==false;if(k==='why')return data.why?.visible!==false;if(k==='process')return data.process?.visible!==false;if(k==='cta')return data.cta?.visible!==false;return data.layout?.sectionVisibility?.[k]!==false};order.forEach((k,i)=>{const el=$(`[data-section-key="${k}"]`);if(el){el.style.order=i+1;el.hidden=!visible(k)}})}

  function openExamples(key){const f=data.features[key],modal=$('[data-modal]');modal.dataset.variant=key;modal.dataset.layout=f.galleryLayout||'editorial';setText('[data-modal-title]',f.examplesTitle||f.title);const items=(f.examples||[]).map((x,i)=>({x,i})).filter(({x})=>x.visible!==false);const mg=$('[data-modal-grid]');mg.className=`modal-grid layout-${f.galleryLayout||'editorial'}`;mg.innerHTML=items.length?items.map(({x,i})=>itemCard(x,key,i,f.galleryLayout,f.showTitles!==false,f.showSubtitles!==false)).join(''):`<div class="empty-gallery">Aún no hay ejemplos publicados.</div>`;modal.hidden=false;document.body.classList.add('modal-open');bindGalleryCards()}
  function closeModal(){const m=$('[data-modal]');if(m){m.hidden=true;document.body.classList.remove('modal-open')}}
  function findItem(kind,id){if(kind==='invitation')return (data.invitationGallery.items||[]).find(x=>String(x.id)===String(id));return (data.features?.[kind]?.examples||[]).find(x=>String(x.id)===String(id))}
  function visibleItemsFor(kind){if(kind==='invitation')return (data.invitationGallery.items||[]).filter(x=>x.visible!==false&&(currentCategory==='Todas'||x.category===currentCategory));return (data.features?.[kind]?.examples||[]).filter(x=>x.visible!==false)}
  function bindGalleryCards(){$$('[data-gallery-item]').forEach(b=>{if(b.dataset.galleryBound==='1')return;b.dataset.galleryBound='1';b.addEventListener('click',e=>{if(previewMode&&editMode)return;const item=findItem(b.dataset.kind,b.dataset.id);if(item)openLightbox(item,b.dataset.kind)})})}
  function renderLightboxItem(){
    const item=lightboxItems[lightboxIndex];if(!item)return;
    const img=$('[data-lightbox-image]');img.classList.remove('portrait','landscape');img.src=item.lightboxImage||item.image||'';img.alt=item.title||'Vista ampliada';img.onload=()=>img.classList.add(img.naturalHeight>img.naturalWidth?'portrait':'landscape');
    setText('[data-lightbox-title]',item.title);setText('[data-lightbox-subtitle]',item.subtitle||'');setText('[data-lightbox-count]',`${lightboxIndex+1} / ${lightboxItems.length}`);
    const link=$('[data-lightbox-link]');if(item.url){link.href=item.url;link.hidden=false}else link.hidden=true;
    $('[data-lightbox-prev]').disabled=lightboxItems.length<2;$('[data-lightbox-next]').disabled=lightboxItems.length<2;
  }
  function openLightbox(item,kind){const l=$('[data-lightbox]');lightboxKind=kind;lightboxItems=visibleItemsFor(kind);lightboxIndex=Math.max(0,lightboxItems.findIndex(x=>String(x.id)===String(item.id)));renderLightboxItem();l.hidden=false;document.body.classList.add('modal-open')}
  function stepLightbox(dir){if(lightboxItems.length<2)return;lightboxIndex=(lightboxIndex+dir+lightboxItems.length)%lightboxItems.length;renderLightboxItem()}
  function closeLightbox(){const l=$('[data-lightbox]');if(l){l.hidden=true;document.body.classList.remove('modal-open')}}
  function scrollGallery(dir){const g=$('[data-gallery-grid]');g.scrollBy({left:dir*Math.max(280,g.clientWidth*.72),behavior:'smooth'})}

  function bindShell(){const mb=$('.menu-btn'),mm=$('[data-mobile-menu]');mb.addEventListener('click',()=>{const on=mm.classList.toggle('open');document.body.classList.toggle('menu-open',on);mb.setAttribute('aria-expanded',String(on));mb.textContent=on?'×':'☰'});mm.addEventListener('click',e=>{if(e.target.closest('a')){mm.classList.remove('open');document.body.classList.remove('menu-open');mb.setAttribute('aria-expanded','false');mb.textContent='☰'}});$$('[data-modal-close]').forEach(x=>x.addEventListener('click',closeModal));$$('[data-lightbox-close]').forEach(x=>x.addEventListener('click',closeLightbox));$('[data-lightbox-prev]').addEventListener('click',()=>stepLightbox(-1));$('[data-lightbox-next]').addEventListener('click',()=>stepLightbox(1));$('[data-gallery-prev]').addEventListener('click',()=>scrollGallery(-1));$('[data-gallery-next]').addEventListener('click',()=>scrollGallery(1));let swipeX=0;const lb=$('[data-lightbox]');lb.addEventListener('pointerdown',e=>{swipeX=e.clientX});lb.addEventListener('pointerup',e=>{const dx=e.clientX-swipeX;if(Math.abs(dx)>55)stepLightbox(dx<0?1:-1)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeLightbox();closeModal()}if(!$('[data-lightbox]').hidden&&e.key==='ArrowLeft')stepLightbox(-1);if(!$('[data-lightbox]').hidden&&e.key==='ArrowRight')stepLightbox(1)})}

  function highlightPath(path){
    $$('.preview-active').forEach(el=>el.classList.remove('preview-active'));
    if(!path)return;let targets=[];try{targets=$$(`[data-edit-key="${CSS.escape(path)}"]`)}catch(e){}
    if(!targets.length&&path.includes('.points')){try{targets=$$(`[data-edit-key="${CSS.escape(path)}"]`)}catch(e){}}
    const first=targets[0];targets.forEach(el=>el.classList.add('preview-active'));if(first&&previewMode){first.scrollIntoView({behavior:'smooth',block:'center'})}
  }
  function bindPreviewEditing(){if(!previewMode)return;document.addEventListener('click',e=>{if(!editMode)return;const target=e.target.closest('[data-edit-key]');if(!target)return;e.preventDefault();e.stopPropagation();parent.postMessage({type:'AURA_EDIT_REQUEST',path:target.dataset.editKey},'*')},true)}
  function setEditMode(on){editMode=Boolean(on);document.documentElement.classList.toggle('preview-edit-mode',editMode);document.body.classList.toggle('preview-edit-mode',editMode)}

  function apply(){window.CURRENT_AURA_DATA=data;applyMeta();applyTheme();renderNav();renderHero();renderServices();renderInvitationGallery();renderFeature('menus');renderFeature('web');renderFeature('galleries');renderWhy();renderProcess();renderCtaFooter();applySectionOrder();setEditMode(editMode)}
  window.addEventListener('message',e=>{const m=e.data||{};if(m.type==='AURA_PREVIEW_STATE'&&m.state){data=deepMerge(structuredClone(base),m.state);setEditMode(Boolean(m.editMode));apply();document.documentElement.classList.remove('aura-preview-await');if(m.highlightPath)highlightPath(m.highlightPath)}else if(m.type==='AURA_HIGHLIGHT_PATH'){highlightPath(m.path)}});
  bindShell();bindPreviewEditing();try{apply()}finally{if(!previewMode)document.documentElement.classList.remove('aura-preview-await')}
})();
